try {
    let resultado = numero * 10;
    console.log(resultado);
} catch(e) {
    console.log("Algo deu errado!");
}